sudo: required
language: java

services:
  - docker

env:
  - DOCKER_IMAGE_NAME=webitel/elasticsearch

before_install:
  - git clone https://github.com/sscarduzio/elasticsearch-readonlyrest-plugin.git
  - cd elasticsearch-readonlyrest-plugin && ./gradlew --stacktrace es63x:ror '-PesVersion=6.5.4'

install:
  - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
  - docker build -t $DOCKER_IMAGE_NAME:6.5.4 .
  - docker build -t $DOCKER_IMAGE_NAME:6.5.4-ROR ROR/

script:
  - docker push $DOCKER_IMAGE_NAME:6.5.4
  - docker push $DOCKER_IMAGE_NAME:6.5.4-ROR
